# Generated by Django 3.1.5 on 2021-01-17 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('s_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('client_name', models.CharField(max_length=100)),
                ('Location', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Projects/')),
                ('project_catg', models.CharField(max_length=100)),
                ('about', models.TextField()),
            ],
        ),
    ]
