# Generated by Django 3.1.5 on 2021-01-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210117_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('download_link', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('feature_1', models.CharField(max_length=100)),
                ('feature_2', models.CharField(max_length=100)),
                ('feature_3', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('d_price', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
